export const ListLoc = {
  forest: {
    name: "Тайный лес",
    position: { x: 500, y: 400 },
    type: "forest",
    discovered: true,
    level: 0,
    icon_sprite: "./assets/loc_sprite.png",
  },
  lake: {
    name: "Озеро слез",
    position: { x: 300, y: 200 },
    type: "water",
    discovered: true,
    level: 1,
    icon_sprite: "./assets/loc_sprite.png",
  },
  eagle_peak: {
    name: "Орлиная вершина",
    position: { x: 800, y: 100 },
    type: "mountain",
    discovered: false,
    level: 2,
    icon_sprite: "./assets/loc_sprite.png",
    unlockRequirement: "pet_level > 3",
  },
  rubikon: {
    name: "<Рубикон>",
    position: { x: 1000, y: 500 },
    type: "tower",
    discovered: true,
    level: 3,
    icon_sprite: "./assets/loc_sprite.png",
  },
  desert_of_night: {
    name: "Пустыня ночи",
    position: { x: 1500, y: 900 },
    type: "sand",
    discovered: false,
    level: 4,
    icon_sprite: "./assets/loc_sprite.png",
  },
  x_island: {
    name: "Остров X",
    position: { x: 1850, y: 750 },
    type: ["forest", "mountain"],
    discovered: true,
    level: 6,
    icon_sprite: "./assets/loc_sprite.png",
  },
};
